name: progress_bars
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  paper_elements: '>=0.7.1 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
  simple_preprocessor: ">=0.0.2 <0.1.0"
transformers:
- simple_preprocessor
- polymer:
    entry_points: web/index.html
